/**
 * Regenerates src/data/image-sizes.ts from the files in public/photos.
 *
 * Layouts frame plates — comic pages and clippings of printed type — at the
 * image's own proportions, which means the build needs to know those
 * proportions without loading every file at render time. Run this after adding
 * or replacing artwork:
 *
 *   npm run image-sizes
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const PHOTOS = path.join(process.cwd(), "public", "photos");
const OUT = path.join(process.cwd(), "src", "data", "image-sizes.ts");

/** Reads width and height out of a JPEG's SOF marker. No dependencies. */
function jpegSize(buffer) {
  let offset = 2;
  while (offset < buffer.length) {
    if (buffer[offset] !== 0xff) {
      offset += 1;
      continue;
    }
    const marker = buffer[offset + 1];
    if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      offset += 2;
      continue;
    }
    const length = buffer.readUInt16BE(offset + 2);
    const isStartOfFrame =
      marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
    if (isStartOfFrame) {
      return { h: buffer.readUInt16BE(offset + 5), w: buffer.readUInt16BE(offset + 7) };
    }
    offset += 2 + length;
  }
  return null;
}

const entries = [];
for (const file of readdirSync(PHOTOS).sort()) {
  const full = path.join(PHOTOS, file);
  if (!statSync(full).isFile() || !/\.jpe?g$/i.test(file)) continue;
  const size = jpegSize(readFileSync(full));
  if (!size) {
    console.warn(`skipped (no SOF marker): ${file}`);
    continue;
  }
  entries.push([`/photos/${file}`, size]);
}

const body = entries.map(([src, { w, h }]) => `  "${src}": { w: ${w}, h: ${h} },`).join("\n");

writeFileSync(
  OUT,
  `/**
 * Intrinsic pixel dimensions of every photograph and page clipping in
 * /public/photos, read straight off the JPEG headers.
 *
 * Layouts use these so an image can be framed at its own proportions instead
 * of a guessed one. That matters for the clippings: they come out of the PDF
 * at every shape from 800x505 to 1200x1670, and a frame with a fixed ratio
 * either crops the type or leaves a hole under it.
 *
 * Generated by scripts/image-sizes.mjs — run \`npm run image-sizes\` after
 * adding artwork rather than editing this file by hand.
 */
export const imageSizes: Record<string, { w: number; h: number }> = {
${body}
};

/** Width / height, or a sane default when the file is not in the table. */
export function aspectOf(src: string, fallback = 3 / 2): number {
  const size = imageSizes[src];
  return size ? size.w / size.h : fallback;
}
`,
);

console.log(`wrote ${entries.length} entries to src/data/image-sizes.ts`);
