/**
 * Intrinsic pixel dimensions of every photograph and page clipping in
 * /public/photos, read straight off the JPEG headers.
 *
 * Layouts use these so an image can be framed at its own proportions instead
 * of a guessed one. That matters for the clippings: they come out of the PDF
 * at every shape from 800x505 to 1200x1670, and a frame with a fixed ratio
 * either crops the type or leaves a hole under it.
 *
 * Generated by scripts/image-sizes.mjs — run `npm run image-sizes` after
 * adding artwork rather than editing this file by hand.
 */
export const imageSizes: Record<string, { w: number; h: number }> = {
  "/photos/7000-steps-a-day.jpg": { w: 1400, h: 877 },
  "/photos/ai-cheating-arms-race.jpg": { w: 1200, h: 815 },
  "/photos/airport-donuts.jpg": { w: 716, h: 588 },
  "/photos/ap-season-over.jpg": { w: 1200, h: 734 },
  "/photos/australia-bans-social-media.jpg": { w: 1400, h: 1392 },
  "/photos/author-of-the-month-sylvia-plath.jpg": { w: 1200, h: 1604 },
  "/photos/benefits-of-morning-running.jpg": { w: 1346, h: 841 },
  "/photos/bible-comics-how-to-pray.jpg": { w: 1035, h: 1361 },
  "/photos/bible-section-the-lord-is-my-shepherd.jpg": { w: 800, h: 505 },
  "/photos/bible-verse-of-the-month.jpg": { w: 800, h: 1200 },
  "/photos/biobites-ocean-life.jpg": { w: 455, h: 460 },
  "/photos/brent-faiyaz-icon.jpg": { w: 348, h: 343 },
  "/photos/buffalo-bills-playoff.jpg": { w: 1120, h: 762 },
  "/photos/cherry-blossom-spots.jpg": { w: 510, h: 637 },
  "/photos/christmas-community-event.jpg": { w: 702, h: 464 },
  "/photos/christmas-gift-guide.jpg": { w: 1240, h: 1233 },
  "/photos/comics-bible-philippians.jpg": { w: 1188, h: 1417 },
  "/photos/crying-in-h-mart.jpg": { w: 1200, h: 801 },
  "/photos/deck-the-doors-winners.jpg": { w: 1200, h: 900 },
  "/photos/does-sungong-time-matter.jpg": { w: 1198, h: 799 },
  "/photos/exercise-stronger-bones.jpg": { w: 1400, h: 935 },
  "/photos/f1-2026-season.jpg": { w: 930, h: 418 },
  "/photos/f1-the-movie.jpg": { w: 615, h: 344 },
  "/photos/fake-productive-study-modes.jpg": { w: 1200, h: 614 },
  "/photos/finals-end-of-year.jpg": { w: 1200, h: 903 },
  "/photos/first-impressions.jpg": { w: 1400, h: 942 },
  "/photos/gamification-trap.jpg": { w: 1400, h: 933 },
  "/photos/god-is-by-ye.jpg": { w: 600, h: 1339 },
  "/photos/green-book.jpg": { w: 1164, h: 701 },
  "/photos/haaland-equals-ronaldos-record.jpg": { w: 842, h: 704 },
  "/photos/home-alone.jpg": { w: 481, h: 280 },
  "/photos/how-dreams-affect-sleep.jpg": { w: 1344, h: 893 },
  "/photos/how-to-beat-the-claw-machine.jpg": { w: 856, h: 423 },
  "/photos/how-to-fall-asleep-quickly.jpg": { w: 1200, h: 800 },
  "/photos/how-to-fix-yourself-crispr.jpg": { w: 1200, h: 732 },
  "/photos/how-to-train-crows-to-steal-coins.jpg": { w: 470, h: 316 },
  "/photos/how-to-wake-up-easier.jpg": { w: 1400, h: 943 },
  "/photos/ill-cross-the-world-to-find-you.jpg": { w: 1196, h: 798 },
  "/photos/imaginary-audience.jpg": { w: 1400, h: 878 },
  "/photos/interview-mr-knickerbocker.jpg": { w: 903, h: 663 },
  "/photos/interview-ms-krebs.jpg": { w: 825, h: 980 },
  "/photos/jeong-and-nunchi.jpg": { w: 717, h: 478 },
  "/photos/kings-warden.jpg": { w: 1400, h: 934 },
  "/photos/lando-norris-champion.jpg": { w: 677, h: 379 },
  "/photos/lord-of-the-flies.jpg": { w: 1200, h: 802 },
  "/photos/malatang-tanghwa-kungfu.jpg": { w: 528, h: 559 },
  "/photos/matcha-overhyped.jpg": { w: 1200, h: 801 },
  "/photos/merry-little-christmas-sinatra.jpg": { w: 368, h: 378 },
  "/photos/mission-site-photo-dump-lipa.jpg": { w: 944, h: 1268 },
  "/photos/mission-trip-site-kenya.jpg": { w: 644, h: 357 },
  "/photos/mission-trip-site-korea.jpg": { w: 1400, h: 927 },
  "/photos/missions-celebration-day.jpg": { w: 1076, h: 583 },
  "/photos/music-while-studying.jpg": { w: 1200, h: 800 },
  "/photos/must-order-delivery-foods.jpg": { w: 1199, h: 800 },
  "/photos/natural-to-koreans.jpg": { w: 1196, h: 798 },
  "/photos/nitroplasts.jpg": { w: 566, h: 271 },
  "/photos/noahs-ark-bible-section.jpg": { w: 1200, h: 1670 },
  "/photos/olivia-rodrigo-two-new-singles.jpg": { w: 350, h: 350 },
  "/photos/peak-end-rule.jpg": { w: 736, h: 736 },
  "/photos/phones-teen-mental-health.jpg": { w: 394, h: 260 },
  "/photos/plastic-pollution.jpg": { w: 922, h: 615 },
  "/photos/prom-2026.jpg": { w: 801, h: 1032 },
  "/photos/psychology-of-procrastination.jpg": { w: 1200, h: 801 },
  "/photos/psychology-of-social-conformity.jpg": { w: 1080, h: 566 },
  "/photos/residential-life-new-schedules.jpg": { w: 960, h: 651 },
  "/photos/rhode-summer-2026.jpg": { w: 396, h: 432 },
  "/photos/romanticise-fall.jpg": { w: 1198, h: 800 },
  "/photos/sheep-wrangling.jpg": { w: 489, h: 369 },
  "/photos/staff-interview-mr-chu.jpg": { w: 1124, h: 742 },
  "/photos/staff-interview-ms-esther-lee.jpg": { w: 1200, h: 1655 },
  "/photos/staff-interview-ms-williams.jpg": { w: 1187, h: 668 },
  "/photos/straw-one-hole-or-two.jpg": { w: 1200, h: 580 },
  "/photos/teen-mental-health-crisis.jpg": { w: 567, h: 375 },
  "/photos/the-greatest-showman.jpg": { w: 1306, h: 815 },
  "/photos/top-school-excuses.jpg": { w: 1200, h: 1655 },
  "/photos/trbl-and-channel-orange.jpg": { w: 1346, h: 815 },
  "/photos/us-military-second-strike.jpg": { w: 433, h: 274 },
  "/photos/vis-bubbly-donations.jpg": { w: 1200, h: 1621 },
  "/photos/why-you-keep-saying-yes.jpg": { w: 1200, h: 930 },
  "/photos/yoon-trial.jpg": { w: 1012, h: 612 },
};

/** Width / height, or a sane default when the file is not in the table. */
export function aspectOf(src: string, fallback = 3 / 2): number {
  const size = imageSizes[src];
  return size ? size.w / size.h : fallback;
}
